[aws]
disabled=true

[elixir]
disabled=true

[lua]
disabled=true

[nodejs]
disabled=true

[elm]
disabled=true

[ruby]
disabled=true

[zig]
disabled=true

[docker_context]
disabled=true

[golang]
disabled=true

[python]
disabled=true

[gcloud]
disabled=true

[git_status]
disabled=true

[git_branch]
format="[$symbol](bold dimmed gray)[$branch]($style) "
style="green"
truncation_length=32

[line_break]
disabled=true

[rust]
disabled=true

[package]
disabled=true

[character]
success_symbol="[❯](bold dimmed gray)"

[directory]
style="gray"
truncation_symbol="…/"
truncation_length=5

[username]
show_always=true
style_user="bold blue"
format="[$user@]($style)"

[hostname]
style="bold blue"
ssh_only=false
format="[$hostname:]($style)"

[jobs]
disabled=true

[cmd_duration]
disabled=true
